# .github/workflows/sbom.yml
name: Generate SBOM
on: [push]
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: syft dir:. --output cyclonedx-json > sbom.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json